# Action to build and publish `backend` image
name: Build and Publish Backend

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Lowercase owner name
        id: repo_owner
        run: echo "owner=${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]' >> $GITHUB_OUTPUT
      - name: Checkout repository from backend repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/KUEater-Backend
          submodules: 'recursive'   # checkout all submodules
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: |
            ghcr.io/${{ steps.repo_owner.outputs.owner }}/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max