# Action to build and publish `postgres` image
name: Build and Publish postgres

on:
  workflow_dispatch:
    inputs:
      pgMajor:
        description: "Major version of PostgreSQL"
        required: true
        type: string
        default: "17"
      vectorsRelease:
        description: "Release tag of `pgvecto.rs` extension prefixed with `v`"
        required: true
        type: string
      uuidv7Release:
        description: "Release tag of `pg_uuidv7` extension prefixed with `v`"
        required: true
        type: string

jobs:
  build-and-publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Lowercase owner name
        id: repo_owner
        run: echo "owner=${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]' >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./postgres
          push: true
          platforms: "linux/amd64"
          file: ./postgres/Dockerfile
          build-args: |
            POSTGRES_MAJOR=${{ github.event.inputs.pgMajor }}
            VECTORS_RELEASE=${{ github.event.inputs.vectorsRelease }}
            UUIDV7_RELEASE=${{ github.event.inputs.uuidv7Release }}
          tags: |
            ghcr.io/${{ steps.repo_owner.outputs.owner }}/postgres:pg${{ github.event.inputs.pgMajor }}-latest
            ghcr.io/${{ steps.repo_owner.outputs.owner }}/postgres:pg${{ github.event.inputs.pgMajor }}-${{ steps.date.outputs.date }}
